config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, except: [:new]
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :load_product, only: [:show, :edit, :update, :destroy]

  def index
    @product = Product.new
    load_all_products
  end

  def create
    @product = Product.new permited_params
    if @product.save
      redirect_to products_path
    else
      load_all_products
      render "index"
    end
  end

  def edit
  end

  def update
    if @product.update_attributes permited_params
      redirect_to products_path
    else
      render "edit"
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def load_all_products
    @products = Product.all.paginate page: params[:page], per_page: 5
  end

  def load_product
    @product = Product.find params[:id]
  end

  def permited_params
    params[:product].permit :name, :description, :price
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title ProductListingApplication
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      h1 Product Listing Application
      hr
      = yield

app/views/products/_product.html.slim
tr
  td= product.name
  td= product.price
  td= product.description
  td
    = link_to "Edit", edit_product_path(product), class: "btn btn-info"
    = link_to "Remove", product_path(product), class: "btn btn-danger", method: :delete

app/views/products/edit.html.slim
h3 Edit product
.edit-form
  = form_for @product do |f|
    ul.errors
      - @product.errors.full_messages.each do |e|
        li= e 
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :price
      = f.text_field :price, class: "form-control"
    .form-group
      = f.label :description
      = f.text_area :description, class: "form-control"
    .form-group
      = f.submit "Save Product", class: "btn btn-success"
      = link_to "Cancel", products_path, class: "btn btn-danger"

app/views/products/index.html.slim
= link_to "Add new product", "#", class: "btn btn-success add-product"
.product-form
  h3 New product
  = form_for @product do |f|
    ul.errors
      - @product.errors.full_messages.each do |e|
        li= e 
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :price
      = f.text_field :price, class: "form-control"
    .form-group
      = f.label :description
      = f.text_area :description, class: "form-control"
    .form-group
      = f.submit "Save Product", class: "btn btn-success"
      = link_to "Cancel", "#", class: "btn btn-danger cancel-form"
hr
table.table.table-striped
  thead
    tr
      th Name
      th Price
      th Description
      th Action
  tbody
    = render @products
= will_paginate @products